package revenueintake

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"errors"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/munisp/blueeconomy-financial-controls/internal/envelope"
)

// fixtureKey is the Ed25519 key the checked-in producer fixture was signed
// with (port-interoperability events.Signer, kid "port-interoperability-1",
// generated by the real producer module — byte-level cross-implementation
// pin for the JWS-over-JCS scheme).
func fixtureSeed() []byte {
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i + 1)
	}
	return seed
}

func fixtureVerifier(t *testing.T) *Verifier {
	t.Helper()
	public := ed25519.NewKeyFromSeed(fixtureSeed()).Public().(ed25519.PublicKey)
	verifier, err := NewVerifier(map[string]ed25519.PublicKey{"port-interoperability-1": public})
	if err != nil {
		t.Fatal(err)
	}
	return verifier
}

func readFixture(t *testing.T) []byte {
	t.Helper()
	raw, err := os.ReadFile("testdata/assessment_envelope.json")
	if err != nil {
		t.Fatal(err)
	}
	return raw
}

// TestProducerFixtureVerifies is the wire-contract pin: an envelope signed
// by the real port-interoperability producer (webpki JCS + Ed25519) verifies
// and maps against this implementation.
func TestProducerFixtureVerifies(t *testing.T) {
	event, err := fixtureVerifier(t).VerifyAndParse(readFixture(t))
	if err != nil {
		t.Fatalf("verify producer fixture: %v", err)
	}
	if event.EventID != "3022e542-9513-4095-924d-69f4176069cb" {
		t.Fatalf("event id = %s", event.EventID)
	}
	if event.EventType != EventTypeAssessmentIssued || event.Producer != Producer {
		t.Fatalf("header: %+v", event)
	}
	if event.SignerKeyID != "port-interoperability-1" {
		t.Fatalf("kid = %s", event.SignerKeyID)
	}
	if event.MappingError != "" {
		t.Fatalf("mapping error: %s", event.MappingError)
	}
	if event.Domain != "OFFSHORE_TERMINAL" || event.CallReference != "SBM-2026-0007" ||
		event.ScheduleID != "sched-offshore-2026Q3" || event.Currency != "USD" {
		t.Fatalf("mapped: %+v", event)
	}
	if event.TotalMinor == nil || *event.TotalMinor != 2500000 {
		t.Fatalf("total: %+v", event.TotalMinor)
	}
	if event.AssessmentID != "a1b2c3d4-0000-4000-8000-0000000000aa" {
		t.Fatalf("assessment id = %s", event.AssessmentID)
	}
	if event.OccurredAt.IsZero() || event.CorrelationID != "sbm-2026-0007-assessment" {
		t.Fatalf("meta: %+v", event)
	}
}

func TestUntrustedKeyRejected(t *testing.T) {
	untrustedPublic, _, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	verifier, err := NewVerifier(map[string]ed25519.PublicKey{"some-other-authority": untrustedPublic})
	if err != nil {
		t.Fatal(err)
	}
	_, err = verifier.VerifyAndParse(readFixture(t))
	if !errors.Is(err, ErrUntrustedKey) {
		t.Fatalf("err = %v, want ErrUntrustedKey", err)
	}
}

func TestMissingSignatureRejected(t *testing.T) {
	var generic map[string]any
	if err := json.Unmarshal(readFixture(t), &generic); err != nil {
		t.Fatal(err)
	}
	generic["provenance"].(map[string]any)["signature"] = ""
	raw, _ := json.Marshal(generic)
	if _, err := fixtureVerifier(t).VerifyAndParse(raw); !errors.Is(err, ErrUntrustedKey) {
		t.Fatalf("err = %v, want ErrUntrustedKey", err)
	}
}

func TestTamperedPayloadRejected(t *testing.T) {
	raw := readFixture(t)
	// Tamper with a signed field after signing.
	tampered := strings.Replace(string(raw), `"2026-08-16T09:30:05Z"`, `"2026-08-16T09:30:06Z"`, 1)
	if tampered == string(raw) {
		t.Fatal("tamper did not apply")
	}
	if _, err := fixtureVerifier(t).VerifyAndParse([]byte(tampered)); !errors.Is(err, ErrSignature) {
		t.Fatalf("err = %v, want ErrSignature", err)
	}
}

func TestMalformedAndUnsupportedRejected(t *testing.T) {
	verifier := fixtureVerifier(t)
	if _, err := verifier.VerifyAndParse([]byte(`{broken`)); !errors.Is(err, ErrMalformed) {
		t.Fatalf("malformed err = %v", err)
	}
	if _, err := verifier.VerifyAndParse(nil); !errors.Is(err, ErrMalformed) {
		t.Fatalf("empty err = %v", err)
	}
	var generic map[string]any
	if err := json.Unmarshal(readFixture(t), &generic); err != nil {
		t.Fatal(err)
	}
	generic["eventType"] = "booking.created"
	raw, _ := json.Marshal(generic)
	if _, err := verifier.VerifyAndParse(raw); !errors.Is(err, ErrUnsupported) {
		t.Fatalf("unsupported err = %v", err)
	}
}

func TestVerifierFromEnvContract(t *testing.T) {
	t.Setenv(TrustedKeysEnv, "")
	if _, err := VerifierFromEnv(); err == nil {
		t.Fatal("empty trusted key env accepted (fail-closed violation)")
	}
	t.Setenv(TrustedKeysEnv, "kid-one=not-a-key")
	if _, err := VerifierFromEnv(); err == nil {
		t.Fatal("malformed key material accepted")
	}
	public := ed25519.NewKeyFromSeed(fixtureSeed()).Public().(ed25519.PublicKey)
	t.Setenv(TrustedKeysEnv, "port-interoperability-1="+base64.RawURLEncoding.EncodeToString(public))
	verifier, err := VerifierFromEnv()
	if err != nil {
		t.Fatal(err)
	}
	if _, err := verifier.VerifyAndParse(readFixture(t)); err != nil {
		t.Fatalf("env verifier rejected fixture: %v", err)
	}
}

// signEvent builds a producer-scheme envelope in-process for variants the
// fixture cannot cover (same JWS-over-JCS scheme, local key).
func signEvent(t *testing.T, kid string, key ed25519.PrivateKey, mutate func(map[string]any)) []byte {
	t.Helper()
	payload := map[string]any{
		"assessment_id":   "b2c3d4e5-0000-4000-8000-0000000000bb",
		"domain":          "CRUISE_DUES",
		"call_reference":  "CRZ-2026-0042",
		"schedule_id":     "sched-cruise-2026Q3",
		"total_minor":     7400000,
		"currency":        "NGN",
		"assessed_by":     "tariff-engine",
		"idempotency_key": "crz-2026-0042-assessment",
	}
	payloadJSON, _ := json.Marshal(payload)
	fhir := map[string]any{
		"resourceType": "Bundle",
		"type":         "message",
		"timestamp":    "2026-08-20T12:00:00Z",
		"entry": []any{map[string]any{
			"fullUrl": "urn:uuid:c3d4e5f6-0000-4000-8000-0000000000cc",
			"resource": map[string]any{
				"resourceType": "Basic",
				"id":           "CRZ-2026-0042",
				"code":         map[string]any{"text": EventTypeAssessmentIssued},
				"extension": []any{
					map[string]any{"url": extensionDomainPayload, "valueString": string(payloadJSON)},
					map[string]any{"url": extensionPrefix + "call-reference", "valueString": "CRZ-2026-0042"},
					map[string]any{"url": extensionPrefix + "currency", "valueString": "NGN"},
					map[string]any{"url": extensionPrefix + "domain", "valueString": "CRUISE_DUES"},
					map[string]any{"url": extensionPrefix + "total-minor", "valueString": "7400000"},
				},
			},
		}},
	}
	envelopeMap := map[string]any{
		"envelopeVersion": EnvelopeVersion,
		"eventId":         "d4e5f6a7-0000-4000-8000-0000000000dd",
		"eventType":       EventTypeAssessmentIssued,
		"occurredAt":      time.Date(2026, 8, 20, 12, 0, 0, 0, time.UTC).Format(time.RFC3339),
		"producer":        Producer,
		"correlationId":   "crz-2026-0042-assessment",
		"classification":  "INTERNAL",
		"fhir":            fhir,
		"provenance":      map[string]any{"principalId": "tariff-engine", "principalRole": "service"},
	}
	if mutate != nil {
		mutate(envelopeMap)
	}
	canonical, err := envelope.JCS(envelopeMap)
	if err != nil {
		t.Fatal(err)
	}
	header, _ := json.Marshal(map[string]string{"alg": "EdDSA", "kid": kid})
	headerPart := base64.RawURLEncoding.EncodeToString(header)
	payloadPart := base64.RawURLEncoding.EncodeToString(canonical)
	signature := ed25519.Sign(key, []byte(headerPart+"."+payloadPart))
	envelopeMap["provenance"].(map[string]any)["signature"] =
		headerPart + "." + payloadPart + "." + base64.RawURLEncoding.EncodeToString(signature)
	raw, _ := json.Marshal(envelopeMap)
	return raw
}

func localVerifier(t *testing.T, kid string, public ed25519.PublicKey) *Verifier {
	t.Helper()
	verifier, err := NewVerifier(map[string]ed25519.PublicKey{kid: public})
	if err != nil {
		t.Fatal(err)
	}
	return verifier
}

// TestLocallySignedCruiseEventVerifies covers the second domain (cruise
// dues) with an NGN total.
func TestLocallySignedCruiseEventVerifies(t *testing.T) {
	public, key, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	raw := signEvent(t, "port-interoperability-7", key, nil)
	event, err := localVerifier(t, "port-interoperability-7", public).VerifyAndParse(raw)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if event.MappingError != "" {
		t.Fatalf("mapping error: %s", event.MappingError)
	}
	if event.Domain != "CRUISE_DUES" || event.Currency != "NGN" || *event.TotalMinor != 7400000 {
		t.Fatalf("mapped: %+v", event)
	}
}

// TestUnmappableEventIsHonest: a validly signed event whose assessment
// cannot be deterministically mapped still verifies — but carries a mapping
// error so the recon pipeline surfaces it instead of guessing.
func TestUnmappableEventIsHonest(t *testing.T) {
	public, key, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	raw := signEvent(t, "port-interoperability-7", key, func(envelopeMap map[string]any) {
		// Contradicting flat extension: the mapping is ambiguous.
		entry := envelopeMap["fhir"].(map[string]any)["entry"].([]any)[0].(map[string]any)
		resource := entry["resource"].(map[string]any)
		extensions := resource["extension"].([]any)
		extensions = append(extensions, map[string]any{
			"url": extensionPrefix + "call-reference", "valueString": "DIFFERENT-REF",
		})
		resource["extension"] = extensions
	})
	event, err := localVerifier(t, "port-interoperability-7", public).VerifyAndParse(raw)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if event.MappingError == "" {
		t.Fatal("contradicting extensions must produce a mapping error")
	}
	if event.TotalMinor != nil {
		t.Fatalf("unmappable event must carry no amount, got %v", *event.TotalMinor)
	}
}

// TestForgedSignatureRejected: a payload signed by an attacker key fails
// against the honest verifier even when the kid is trusted.
func TestForgedSignatureRejected(t *testing.T) {
	public, _, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	_, attackerKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	raw := signEvent(t, "port-interoperability-7", attackerKey, nil)
	if _, err := localVerifier(t, "port-interoperability-7", public).VerifyAndParse(raw); !errors.Is(err, ErrSignature) {
		t.Fatalf("err = %v, want ErrSignature", err)
	}
}
